name: 'js-profile-updater'
description: 'Updates your profile README.md with provided latest youtube channel videos.'
inputs:
  youtubeChannelId:
    description: 'The ID of the channel.'
    required: true

branding:
  icon: activity
  color: green

runs:
  using: 'node12'
  main: 'index.js'
